apiVersion: apps/v1
kind: Deployment
metadata:
  name: beproduct-deployment
  labels:
    app: beproduct
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beproduct
  template:
    metadata:
      labels:
        app: beproduct
    spec:
      containers:
        - name: beproduct
          image: 192.168.1.X:6300/beproduct:1.0
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: my-secret
          resources:
            limits:
              cpu: 500m
              memory: 900Mi
            requests:
              cpu: 250m
              memory: 512Mi       
      imagePullSecrets:
        - name: regcred
        
