apiVersion: apps/v1
kind: Deployment
metadata:
  name: beproduct-deployment
  labels:
    app: beproduct
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beproduct
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: beproduct
    spec:
      containers:
        - name: beproduct
          image: 10.100.244.174:6300/beproduct_jenkins_secret:1.0
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 500m
              memory: 900Mi
            requests:
              cpu: 250m
              memory: 512Mi
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: beproduct-secret
                  key: NODE_ENV
            - name: USER_DB
              valueFrom:
                secretKeyRef:
                  name: beproduct-secret
                  key: USER_DB
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: beproduct-secret
                  key: PORT               
            - name: PASSWORD_DB
              valueFrom:
                secretKeyRef:
                  name: beproduct-secret
                  key: PASSWORD_DB
      imagePullSecrets:
        - name: regcred
