apiVersion: apps/v1
kind: Deployment
metadata:
  name: beproduct-deployment
  labels:
    app: beproduct
spec:
  selector:
    matchLabels:
      app: beproduct
  template:
    metadata:
      labels:
        app: beproduct
    spec:
      containers:
      - name: beproduct
        image: lapisan/beproduct:1.0
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        env:
         - name: NODE_ENV
           valueFrom:
            secretKeyRef:
              name: beproduct-secret
              key: NODE_ENV
         - name: HOST
           valueFrom:
            secretKeyRef:
              name: beproduct-secret
              key: HOST
         - name: PORT
           valueFrom:
            secretKeyRef:
              name: beproduct-secret
              key: PORT               
         - name: DB_NAME
           valueFrom:
            secretKeyRef:
              name: beproduct-secret
              key: DB_NAME
         - name: DB_USER
           valueFrom:
            secretKeyRef:
              name: beproduct-secret
              key: DB_USER
         - name: DB_PASSWORD
           valueFrom:
            secretKeyRef:
              name: beproduct-secret
              key: DB_PASSWORD
         - name: DB_HOST
           valueFrom:
            secretKeyRef:
              name: beproduct-secret
              key: DB_HOST 