apiVersion: apps/v1
kind: Deployment
metadata:
  name: feproduct-deployment
  labels:
    app: feproduct
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feproduct
  template:
    metadata:
      labels:
        app: feproduct
    spec:
      containers:
        - name: feproduct
          image: 192.168.1.8:6300/feproduct:1.0
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
        